# Generated by Django 5.0.6 on 2024-07-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_name", models.CharField(max_length=50)),
                ("timing", models.TimeField()),
                ("date", models.DateField()),
                ("order_id", models.CharField(max_length=50)),
                ("amount", models.IntegerField()),
                ("address_code", models.CharField(max_length=50)),
                (
                    "cancel_status",
                    models.CharField(
                        choices=[("non-cancel", "Non-Cancel"), ("cancel", "Cancel")],
                        default="non-cancel",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
