# Generated by Django 5.0.6 on 2024-07-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="refresh_link",
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
    ]
