# Generated by Django 5.0.6 on 2024-07-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_order_refresh_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.CharField(max_length=500),
        ),
    ]
